### ISSUE TITLE
Handle large number of links

### ISSUE THREAD

**Issue by jasonyates-thg** [netreplica/nrx#48]
When running against a large topology with 10+ devices and many cables the export fails with the error

Error: NetBox API failure at get cables: The request failed with code 414 Request-URI Too Large but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.

**Comment by bortok** [comment]
Hi @jasonyates-thg, thanks for submitting the bug report! I have a few clarifying questions:

- how many cables are we talking about? 
- are they directly connected to device interfaces, or do they connect to patch panels, circuits etc?
- do you want to export all the cables, or would an option to specify which interfaces/cables to export via a tag be helpful?

**Comment by jasonyates-thg** [comment]
* 100+ cables for a particular topology. 
* They are directly connected between devices. I'm attempting to visualise a spine leaf topology with ~20 leaf switches.
* All cables would be helpful. 

Looking at the code, it appears to try and grab all cables at the same time which i'm guessing generates a huge URL, perhaps putting that in a loop and grabbing 50 cables at a time would be easier to accomplish.

**Comment by bortok** [comment]
Problematic code: https://github.com/netreplica/nrx/blob/main/nrx/nrx.py#L311

```
for cable in list(self.nb_session.dcim.cables.filter(id=self.nb_net.cable_ids)):
```

Need to iterate over `self.nb_net.cable_ids` in chunks small enough to fit a URL, but large enough to minimize the number of API calls. Start with a size known to usually fit, but watch for `414` return code – if encountered, halve the size and try again.

**Comment by bortok** [comment]
Hi @jasonyates-thg would you be able to try the fix in `scale-cables` branch? To get the fix, from the cloned repository run:
```
git pull
git checkout scale-cables
```

**Comment by bortok** [comment]
Thanks! Will be available in the next release
