### ISSUE TITLE
Allow multi-site export

### ISSUE THREAD

**Issue by scotho3** [netreplica/nrx#84]
Having a single site is nice, but for backbones or other large interconnected networks, having a single topology showing all sites, or multiple sites would be helpful.

**Comment by bortok** [comment]
Scott, could you propose how the CLI command would look like? Also, if the sites are disconnected (two or more graphs) would that change anything in the export logic? Note, today nrx does not export standalone devices (w/o connections to other devices in the same export group).

**Comment by scotho3** [comment]
`./nrx.py --sites site1,site2,site3 ...` was what I had in mind. 

If they're not connected, they're not connected, I think the default behavior for standalone devices is fine, although I could make an argument for showing them. 

https://github.com/scotho3/nrx - is an example.

**Comment by bortok** [comment]
Thomas, if you would create a PR, I shall be able to test it next weekend and give more feedback. Thank you for the suggestion!

**Comment by bortok** [comment]
Hi @scotho3 , would you be able to create a PR for this?

**Comment by scotho3** [comment]
Hi @bortok - sorry, I was away from my email for an extended holiday, [PR](https://github.com/netreplica/nrx/pull/88) has been opened.
